name: Pull Request

on:
  pull_request:

jobs:
  pack-microcluster-token-distributor:
    uses: canonical/microcluster-token-distributor-operator/.github/workflows/pack.yaml@main
    with:
      name: microcluster-token-distributor
      path: token-distributor
  pack-microovn:
    uses: canonical/microcluster-token-distributor-operator/.github/workflows/pack.yaml@main
    with:
      name: microovn
      path: microovn
  test:
    runs-on: [ ubuntu-latest, large ]
    needs:
      - pack-microcluster-token-distributor
      - pack-microovn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: microcluster-token-distributor
      - uses: actions/download-artifact@v4
        with:
          name: microovn

      - name: Set charm paths
        run: |
          set -- ${{ needs.pack-microovn.outputs.charms }}
          echo "MICROOVN_CHARM_PATH=$1" >> $GITHUB_ENV
          set -- ${{ needs.pack-microcluster-token-distributor.outputs.charms }}
          echo "TOKEN_DISTRIBUTOR_CHARM_PATH=$1" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt -yqq install tox
          sudo snap install concierge --classic
          sudo apt install python3-pytest
          # install jubilant in a nicer way when its in apt/snap
          pip install jubilant --break-system-packages

      - name: Prepare Environment for functional tests
        run: |
          # Use concierge to setup LXD, microk8s and bootstrap juju controller
          cat <<EOF >>/tmp/concierge.yaml
          juju:
            channel: 3.5/stable

          providers:
            microk8s:
              enable: true
              bootstrap: false
              addons:
                - dns
                - hostpath-storage
                - metallb

            lxd:
              enable: true
              bootstrap: true
          EOF

          sudo concierge prepare -c /tmp/concierge.yaml

          # Create second bridged network needed by the functional tests
          lxc network create second --type=bridge

          # Add microk8s as a kubernetes substrate to the Juju controller
          sudo microk8s status --wait
          # The kubernetes API is not always immediately available to use, even if
          # microk8s status reports ready state. These retries ensure that we don't
          # fail the test unnecessarily
          (r=30;while ! juju add-k8s mk8s --controller concierge-lxd ; do ((--r))||exit;sleep 2;done)

      - name: Run test
        run: pytest tests
